---
title: "Summary: Model 4b"
author: "Jesse Birchfield"
date: "6/11/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstan) 
library(gt)

modelName <- "model4b"
BirchfieldDirectory <- 'D:/Documents/_UCLA/Holbrook/CrossLong/Birchfield/'
setwd(BirchfieldDirectory)
modelFit <- readRDS(paste0("model4/", modelName, "Fit.rds"))

```
\n\n
```{r, echo=FALSE}

parsOfInterest <- c(
  "alpha_0",
  "lambda_0",
  "alpha_1",
  "lambda_1",
  "beta_mci",
  "beta_ad",
  "beta_mci_t",
  "beta_ad_t",
  "sigma",
  "bias",
  "tau",
  "nu")

modelSamples <- rstan::extract(modelFit, pars=parsOfInterest) %>% as.data.frame()

modelSummary <- modelFit %>% 
  summary(pars=parsOfInterest) %>% 
  `[[`(1) %>% 
  data.frame() %>% 
  select(c(1,3,4,8,9)) %>% 
  round(4) %>% 
  rename(`2.5%`=X2.5., `97.5%`=X97.5.)

modelTable <- modelSummary %>% 
  gt(rownames_to_stub = TRUE) %>%
  tab_header(title=paste0("posterior summary, ", modelName),
             subtitle="chains: 1,  iterations: 5000,  warmup: 1000") %>%
  tab_source_note(source_note="1. FSCross") %>%
  tab_source_note(source_note="2. FSLong") %>%
  tab_source_note(source_note="3. ANTsCross") %>%
  tab_source_note(source_note="4. ANTsNative") %>%
  tab_source_note(source_note="5. ANTsSST") %>%
  tab_source_note(source_note="6. ANTsXNetCross") %>%
  tab_source_note(source_note="7. ANTSsXNetLong")

modelTable

#gtsave(modelTable, paste0(modelName, "Table.html"))

```
\n\n
```{r, echo=FALSE}

tauSamples <- modelFit %>% 
  rstan::extract(pars="tau") %>% 
  `[[`(1) %>% 
  data.frame()

tauSamplesToPlot <- with(tauSamples,
  data.frame(
    x = c(X1,
          X2,
          X3,
          X4,
          X5,
          X6,
          X7),
    pipeline = c(rep("FSCross", length(X1)),
          rep("FSLong", length(X2)),
          rep("ANTsCross", length(X3)),
          rep("ANTsNative", length(X4)),
          rep("ANTsSST", length(X5)),
          rep("ANTsXNetCross", length(X6)),
          rep("ANTsXNetLong", length(X7)))
  ))

tauSamplesToPlot$pipeline <- factor(
  tauSamplesToPlot$pipeline,
  levels = c(
    'FSCross',
    'FSLong',
    'ANTsCross',
    'ANTsNative',
    'ANTsSST',
    'ANTsXNetCross',
    'ANTsXNetLong'))

ggplot(tauSamplesToPlot, aes(x, fill=pipeline)) + 
  geom_density(alpha=0.25) + 
  xlab("tau") + 
  ggtitle(modelName)

```

\n\n
```{r, echo=FALSE}

nuSamples <- modelFit %>% 
  rstan::extract(pars="nu") %>% 
  `[[`(1) %>% 
  data.frame()

nuSamplesToPlot <- with(nuSamples,
  data.frame(
    x = c(X1,
          X2,
          X3,
          X4,
          X5,
          X6,
          X7),
    pipeline = c(rep("FSCross", length(X1)),
          rep("FSLong", length(X2)),
          rep("ANTsCross", length(X3)),
          rep("ANTsNative", length(X4)),
          rep("ANTsSST", length(X5)),
          rep("ANTsXNetCross", length(X6)),
          rep("ANTsXNetLong", length(X7)))
  ))

nuSamplesToPlot$pipeline <- factor(
  nuSamplesToPlot$pipeline,
  levels = c(
    'FSCross',
    'FSLong',
    'ANTsCross',
    'ANTsNative',
    'ANTsSST',
    'ANTsXNetCross',
    'ANTsXNetLong'))

ggplot(nuSamplesToPlot, aes(x, fill=pipeline)) + 
  geom_density(alpha=0.25) + 
  xlab("nu") + 
  ggtitle(modelName)

```

```{r, echo=FALSE}
biasSamples <- modelFit %>% 
  rstan::extract(pars="bias") %>% 
  `[[`(1) %>% 
  data.frame()

biasSamplesToPlot <- with(biasSamples,
  data.frame(
    x = c(X1,
          X2,
          X3,
          X4,
          X5,
          X6),
    pipeline = c(rep("FSCross", length(X1)),
          rep("FSLong", length(X2)),
          rep("ANTsCross", length(X3)),
          rep("ANTsNative", length(X4)),
          rep("ANTsSST", length(X5)),
          rep("ANTsXNetCross", length(X6)))
  ))

biasSamplesToPlot$pipeline <- factor(
  biasSamplesToPlot$pipeline,
  levels = c(
    'FSCross',
    'FSLong',
    'ANTsCross',
    'ANTsNative',
    'ANTsSST',
    'ANTsXNetCross'
    ))

ggplot(biasSamplesToPlot, aes(x, fill=pipeline)) + 
  geom_density(alpha=0.25) + 
  xlab("bias") + 
  ggtitle(modelName)

```