


# Appendix


## Implementation overview

The script ``antsLongitudinalCorticalThickness.sh`` performs cortical thickness
estimation for a longitudinal image series from a single subject.  The following
principal steps are performed:

1. A single-subject template (SST) is created from all the time point images.
2. The tissue prior probability images are generated for the SST. These six tissues are
   label 1:  CSF, label 2: cortical gray matter, label 3: white matter, label 4: deep
   gray matter, label 5: brain stem, and label 6: cerebellum.  Prior probability creation
   involves the following steps:  

    1. The SST is passed through ``antsCorticalThicknes.sh``.
    2. The brain extraction posterior for the SST is created by smoothing the brain extraction
       mask created during 2a.
    3. If labeled atlases are not provided, we smooth the posteriors from 2.1 to create
       the SST segmentation priors, otherwise we use the ``antsJointFusion`` program
       to create a set of posteriors using the script ``antsCookTemplatePriors.sh``.

3. Using the SST + priors, each subject is processed through the ``antsCorticalThickness.sh``
   script.

A typical command line call is:
```
antsLongitudinalCorticalThickness.sh \
              -d ${imageDimension} \
              -e ${brainTemplate} \
              -m ${brainExtractionProbabilityMask} \
              -p ${brainSegmentationPriors}
              -o ${outputPrefix}
              ${anatomicalImages[@]}
```

## Input parameters

* ``imageDimension``:  dimensionality of the input images.  Can handle 2 or 3 dimensions.
* ``brainTemplate``:  the group template.  We have made several publicly available
along with the prior tissue and brain extraction images
(https://figshare.com/articles/ANTs_ANTsR_Brain_Templates/915436).
* ``brainExtractionProbabilityMask``:  prior probability image for the whole brain
corresponding to the ``brainTemplate``.
* ``brainSegmentationPriors``:  prior probability images for the six brain tissues
mentioned above.  These files are specified with the relevant labels, e.g., ``prior1.nii.gz``,
``prior2.nii.gz``, ``prior3.nii.gz``, ``prior4.nii.gz``, ``prior5.nii.gz``,
and ``prior6.nii.gz``.  The command line argument is specified in C-style formatting, e.g.,
``prior%d.nii.gz``.
* ``anatomicalImages``:  the time point images for a single subjects.
* other optional input parameters are available.  ``antsLongitudinalCorticalThickness -h``
  provides a listing of the full set of parameters, their descriptions, and other help information.

## Output

In the specified output directory, the following subdirectories are created:

* ``${outputPrefix}SST``
* ``${outputPrefix}${anatomicalImagesPrefix[0]}``
* ``${outputPrefix}${anatomicalImagesPrefix[1]}``
* ``${outputPrefix}${anatomicalImagesPrefix[2]}``
* ...

Each subdirectory contains the output of `antsCorticalThickness.sh` applied to the
corresponding image.  Output consists of the following files:

* `BrainExtractionMask`: Brain extraction mask in subject space.
* `BrainNormalizedToTemplate`: Extracted brain image normalized to the template space.
* `BrainSegmentation0N4`: Input to the segmentation algorithm. It is not brain extracted, but is bias-corrected. If multiple images are used for segmentation, there will be `BrainSegmentation1N4` and so on. The brain extracted version of this is `ExtractedBrain0N4`.
* `BrainSegmentation`: Segmentation image, one label per tissue class. The number of classes is determined by the input priors.
* `BrainSegmentationPosteriors1`: Posterior probability of class 1. A similar image is produced for all classes. The numbering scheme matches the input priors.
* `CorticalThickness`: Cortical thickness image in subject space.
* `CorticalThicknessNormalizedToTemplate`: Cortical thickness image in template space.
* `ExtractedBrain0N4`: Brain-extracted version of `BrainSegmentation0N4`.
* `SubjectToTemplate1Warp`, `SubjectToTemplate0GenericAffine.mat`:  Transforms to be used when warping images from the subject space to the template space.
* `SubjectToTemplateLogJacobian`: Log of the determinant of the Jacobian, quantifies volume changes in the subject to template warp.
* `TemplateToSubject0Warp`, `TemplateToSubject1GenericAffine.mat`: Transforms to be used when warping images from the template to the subject space.


In addition to these files, the SST subdirectory contains additional warps, suffixed "SubjectToGroupTemplateWarp.nii.gz" and "SubjectToTemplate0GenericAffine.mat", that can be used to warp each time point image to the group template. These are a combination of the subject to SST warp, and the SST to group template warp.  Also included are the SST brain and tissue prior probability images.  



\clearpage
