---
title: "Summary: Model 3 revised"
author: "Jesse Birchfield"
date: "6/22/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstan) 
library(gt)
```
\n\n
```{r, echo=FALSE}

model3Fit <- readRDS("model3Fit.rds")

parsOfInterest <- c(
  "alpha_0",
  "lambda_0",
  "alpha_1",
  "lambda_1",
  "beta_mci",
  "beta_ad",
  "beta_age",
  "beta_male",
  "beta_mci_t",
  "beta_ad_t",
  "sigma",
  "tau",
  "nu")

#model3Samples <- rstan::extract(model3Fit, pars=parsOfInterest) %>% as.data.frame()

model3Summary <- model3Fit %>% 
  summary(pars=parsOfInterest) %>% 
  `[[`(1) %>% 
  data.frame() %>% 
  select(c(1,3,4,8,9)) %>% 
  round(4) %>% 
  rename(`2.5%`=X2.5., `97.5%`=X97.5.)

model3Summary %>% 
  gt(rownames_to_stub = TRUE) %>%
  tab_header(title="posterior summary, model 3",
             subtitle="chains: 4,  iterations: 20k,  warmup: 10k") %>%
  tab_source_note(source_note="1. FSCross") %>%
  tab_source_note(source_note="2. FSLong") %>%
  tab_source_note(source_note="3. ANTsCross") %>%
  tab_source_note(source_note="4. ANTsNative") %>%
  tab_source_note(source_note="5. ANTsSST") %>%
  tab_source_note(source_note="6. ANTsXNetCross") %>%
  tab_source_note(source_note="7. ANTSsXNetLong")

```
\n\n
```{r, echo=FALSE}

tauSamples <- model3Fit %>% 
  rstan::extract(pars="tau") %>% 
  `[[`(1) %>% 
  data.frame()

tauSamplesToPlot <- with(tauSamples,
  data.frame(
    x = c(X1,
          X2,
          X3,
          X4,
          X5,
          X6,
          X7),
    pipeline = c(rep("FSCross", length(X1)),
          rep("FSLong", length(X2)),
          rep("ANTsCross", length(X3)),
          rep("ANTsNative", length(X4)),
          rep("ANTsSST", length(X5)),
          rep("ANTsXNetCross", length(X6)),
          rep("ANTsXNetLong", length(X7)))
  ))

tauSamplesToPlot$pipeline <- factor(
  tauSamplesToPlot$pipeline,
  levels = c(
    'FSCross',
    'FSLong',
    'ANTsCross',
    'ANTsNative',
    'ANTsSST',
    'ANTsXNetCross',
    'ANTsXNetLong'))

ggplot(tauSamplesToPlot, aes(x, fill=pipeline)) + 
  geom_density(alpha=0.25) + 
  xlab("tau") + 
  ggtitle("model 3")

```

\n\n
```{r, echo=FALSE}

nuSamples <- model3Fit %>% 
  rstan::extract(pars="nu") %>% 
  `[[`(1) %>% 
  data.frame()

nuSamplesToPlot <- with(nuSamples,
  data.frame(
    x = c(X1,
          X2,
          X3,
          X4,
          X5,
          X6,
          X7),
    pipeline = c(rep("FSCross", length(X1)),
          rep("FSLong", length(X2)),
          rep("ANTsCross", length(X3)),
          rep("ANTsNative", length(X4)),
          rep("ANTsSST", length(X5)),
          rep("ANTsXNetCross", length(X6)),
          rep("ANTsXNetLong", length(X7)))
  ))

nuSamplesToPlot$pipeline <- factor(
  nuSamplesToPlot$pipeline,
  levels = c(
    'FSCross',
    'FSLong',
    'ANTsCross',
    'ANTsNative',
    'ANTsSST',
    'ANTsXNetCross',
    'ANTsXNetLong'))

ggplot(nuSamplesToPlot, aes(x, fill=pipeline)) + 
  geom_density(alpha=0.25) + 
  xlab("nu") + 
  ggtitle("model 3")

```

```{r, echo=FALSE}

traceplot(model3Fit, pars=c("alpha_0", "lambda_0", "alpha_1", "lambda_1", "sigma"), inc_warmup=T)

traceplot(model3Fit, pars=c("beta_mci", "beta_ad", "beta_mci_t", "beta_ad_t", "beta_age", "beta_male"), inc_warmup=T)

traceplot(model3Fit, pars=c("tau"), inc_warmup=T)

traceplot(model3Fit, pars=c("nu"), inc_warmup=T)


```
```{r}

traceplot(model3Fit, pars="alpha_1")


```
